name: Análisis de SonarQube

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Consulta el código fuente
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Analizar con SonarQube
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

        with:
          args: >
            -Dsonar.projectKey=marianasena1002-beep_Venta-de-Celulares-M
            -Dsonar.organization=marianasena1002-beep
